# -*- coding: utf-8 -*-
"""TubesVisdat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16bkREGHddcxcprB0UfEGUFNhpZ3j0xtH
"""

import pandas as pd
from bokeh.io import curdoc, output_notebook, output_file
from bokeh.plotting import figure, reset_output, show
from bokeh.models import HoverTool, ColumnDataSource, GeoJSONDataSource, CustomJS, LabelSet
from bokeh.models import CategoricalColorMapper, Dropdown, ColorBar, Patches, LinearColorMapper
from bokeh.models.widgets import DataTable, TableColumn
from bokeh.palettes import Spectral6
from bokeh.layouts import widgetbox, row, gridplot
from bokeh.models import Slider, Select
import bokeh.layouts

df_covid = pd.read_csv("covid_19_clean_complete.csv")
df_covid.drop(columns=["Province/State", "Lat", "Long", "WHO Region"], axis=0, inplace=True)
df_covid.rename(columns={"Country/Region": "Country"}, inplace=True)
df_covid['Date'] = pd.to_datetime(df_covid['Date'])
df_covid.sample(5)

def data_source(selected_country):
  data=df_covid[df_covid["Country"]==selected_country]
  source={
      "Country":data["Country"],
      "Date":data["Date"],
      "Confirmed":data["Confirmed"],
      "Deaths":data["Deaths"],
      "Recovered":data["Recovered"],
      "Active":data["Active"]
  }
  return source

def update_plot(attr,old,new):
  Country=Dropdown_menu.value
  source.data=data_source(Country)

country_list=df_covid.Country.unique().tolist()
Dropdown_menu=Select(
    options=country_list,
    value="Indonesia",
    title="Country",
)
Dropdown_menu.on_change("value",update_plot)

source=ColumnDataSource(data_source("Indonesia"))

output_notebook()
fig = figure(x_axis_type='datetime',
             plot_height=350, plot_width=700,
             title='Statistic Kasus Covid19 2020',
             x_axis_label='Date', y_axis_label='Total', tools = ['pan, wheel_zoom, box_zoom, reset'])
fig.title.text_font_size="14pt"
fig.title.align="center"
line1=fig.line(x="Date", y="Confirmed", color="#00FFFF",line_width=2, legend_label="Confirmed", source=source)
line2=fig.line(x="Date", y="Deaths", color="#FF0000",line_width=2, legend_label="Deaths", source=source)
line3=fig.line(x="Date", y="Recovered", color="#50C878",line_width=2, legend_label="Recovered", source=source)
line4=fig.line(x="Date", y="Active", color="#40E0D0",line_width=2, legend_label="Active", source=source)

fig.add_tools(HoverTool(renderers=[line1], tooltips = [('Date', '@Date{%F}'), 
                                                     ('Confirmed', '@Confirmed')],
                                         formatters={'@Date': 'datetime'}))
fig.add_tools(HoverTool(renderers=[line2], tooltips = [('Date', '@Date{%F}'), 
                                                     ('Deaths', '@Deaths')],
                                         formatters={'@Date': 'datetime'}))
fig.add_tools(HoverTool(renderers=[line3], tooltips = [('Date', '@Date{%F}'), 
                                                     ('Recovered', '@Recovered')],
                                         formatters={'@Date': 'datetime'}))
fig.add_tools(HoverTool(renderers=[line4], tooltips = [('Date', '@Date{%F}'), 
                                                     ('Active', '@Active')],
                                         formatters={'@Date': 'datetime'}))

fig.legend.location="top_left"
layout=row(widgetbox(fig,Dropdown_menu))
curdoc().add_root(layout)
show(fig)

